version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 575279257907.dkr.ecr.us-east-2.amazonaws.com/public_repo
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t 575279257907.dkr.ecr.us-east-2.amazonaws.com/public_repo:latest .
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 575279257907.dkr.ecr.us-east-2.amazonaws.com/public_repo:latest
      - echo Build completed on `date`
artifacts:
  files:
    - imagedefinitions.json
